
export const CONSTANTS = {
    UNIT_TO_PX_SCALE: 30,
    BOMB_DEFAULT_REACH_BLOCKS: 3,
    BOMB_DEFAULT_TIME_TO_EXPLODE_IN_MS: 2000,
    BOMB_DEFAULT_TIME_TO_LIVE: 3000,
    BOMB_DAMAGE_PERCENT_ON_PLAYER: 50
}
